.TH "D:/work/AIDA2EDDYONE/WindowsFormsApplication2/WindowsFormsApplication2/Form1.Designer.cs" 3 "Mon Dec 5 2016" "Docs_create" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/work/AIDA2EDDYONE/WindowsFormsApplication2/WindowsFormsApplication2/Form1.Designer.cs \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBWindowsFormsApplication2\&.Form1\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBWindowsFormsApplication2\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Docs_create from the source code\&.
