.TH "D:/work/AIDA2EDDYONE/WindowsFormsApplication2/WindowsFormsApplication2/Properties/Resources.Designer.cs" 3 "Mon Dec 5 2016" "Docs_create" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/work/AIDA2EDDYONE/WindowsFormsApplication2/WindowsFormsApplication2/Properties/Resources.Designer.cs \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBWindowsFormsApplication2\&.Properties\&.Resources\fP"
.br
.RI "A strongly-typed resource class, for looking up localized strings, etc\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBWindowsFormsApplication2\&.Properties\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Docs_create from the source code\&.
