.TH "WindowsFormsApplication2.Form1" 3 "Mon Dec 5 2016" "Docs_create" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WindowsFormsApplication2.Form1 \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Form\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBForm1\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBMakeWord\fP (byte low, byte high)"
.br
.RI "create int from 2 bytes, little endian format "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBDispose\fP (bool disposing)"
.br
.RI "Clean up any resources being used\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBSeries1\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18 of file Form1\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "WindowsFormsApplication2\&.Form1\&.Form1 ()"

.PP
Definition at line 22 of file Form1\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "override void WindowsFormsApplication2\&.Form1\&.Dispose (bool disposing)\fC [protected]\fP"

.PP
Clean up any resources being used\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdisposing\fP true if managed resources should be disposed; otherwise, false\&.
.RE
.PP

.PP
Definition at line 14 of file Form1\&.Designer\&.cs\&.
.SS "static int WindowsFormsApplication2\&.Form1\&.MakeWord (byte low, byte high)\fC [static]\fP"

.PP
create int from 2 bytes, little endian format 
.PP
Definition at line 209 of file Form1\&.cs\&.
.SH "Property Documentation"
.PP 
.SS "string WindowsFormsApplication2\&.Form1\&.Series1\fC [get]\fP"

.PP
Definition at line 20 of file Form1\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Docs_create from the source code\&.
